---
  - name: install bench
    pip: name={{ bench_repo_path }} extra_args='-e'
    become: yes
    become_user: root

  - name: Check whether bench exists
    stat: path="{{ bench_path }}"
    register: bench_stat

  - name: init bench
    command: bench init {{ bench_path }} --frappe-branch {{ branch }}
    args:
      creates: "{{ bench_path }}"
    when: not bench_stat.stat.exists

  # setup common_site_config
  - name: setup config
    command: bench setup config
    args:
      creates: "{{ bench_path }}/sites/common_site_config.json"
      chdir: "{{ bench_path }}"

  - name: install frappe app
    command: bench get-app frappe https://github.com/frappe/frappe
    args:
      creates: "{{ bench_path }}/apps/frappe"
      chdir: "{{ bench_path }}"
