---
  - name: install bench
    pip: name={{ bench_repo_path }} extra_args='-e'
    become: yes
    become_user: root

  - name: init bench
    command: bench init {{ bench_path }}
    args:
      creates: "{{ bench_path }}"

  - name: Get ERPNext Application
    command: bench get-app erpnext https://github.com/frappe/erpnext.git
    args:
        chdir: "{{ bench_path }}"
    when: '{{ setup_production }}'

  # After initializing the bench, setup the first site for the user in case of production setup
  - name: Setup first site
    command: bench new-site site1.local --mariadb_root_password {{ mysql_root_password }} --admin-password {{ admin_password }}
    args:
      chdir: "{{ bench_path }}"
    when: '{{ setup_production }}'

  # Install ERPNext Application
  - name: Install ERPNext Application
    command: bench --site {{ site_name }} install-app erpnext
    args:
        chdir: "{{ bench_path }}"
    when: '{{ setup_production }}'

  # Setup Sudoers
  - name: Setup sudoers
    command: bench setup sudoers '{{ frappe_user }}'
    args:
        chdir: "{{ bench_path }}"
    become: yes
    become_user: root
    when: '{{ setup_production }}'

  # Setup production
  - name: Setup production
    command: bench setup production '{{ frappe_user }}'
    args:
        chdir: "{{ bench_path }}"
    become: yes
    become_user: root
    when: '{{ setup_production }}'

  # Change the ownership for {bench}/logs folder from root to frappe
  - name: Change the ownership for logs folders
    file:
        path: "{{ bench_path }}/logs"
        owner: '{{ frappe_user }}'
        group: frappe
        mode: 0755
        recurse: yes

  # setup common_site_config
  - name: setup config
    command: bench setup config
    args:
      creates: "{{ bench_path }}/sites/common_site_config.json"
      chdir: "{{ bench_path }}"

  # setup socketio
  - name: setup procfile
    command: bench setup socketio
    args:
      creates: "{{ bench_path }}/node_modules"
      chdir: "{{ bench_path }}"

  # setup config for redis/socketio
  - name: setup redis
    command: bench setup redis
    args:
      creates: "{{ bench_path }}/config/redis_socketio.conf"
      chdir: "{{ bench_path }}"

  - name: install frappe app
    command: bench get-app frappe https://github.com/frappe/frappe
    args:
      creates: "{{ bench_path }}/apps/frappe"
      chdir: "{{ bench_path }}"
    when: not '{{ setup_production }}'
  # This needs to be done only in case of development setup, as we install frappe while we create
  # a new-site.

  # setup procfile
  - name: setup procfile
    command: bench setup procfile
    args:
      creates: "{{ bench_path }}/Procfile"
      chdir: "{{ bench_path }}"
    when: not '{{ setup_production }}'
