---
- hosts: localhost
  become: root
  become_method: sudo
  vars_prompt:
    - name: mysql_root_password
      prompt: "Enter root password for MySQL"
      when: ansible_distribution == 'Ubuntu'

- include: macosx.yml
  when: ansible_distribution == 'MacOSX'
- include: ubuntu.yml
  when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'
- include: centos.yml
  when: ansible_distribution == 'CentOS'
